"""Shadow PR service for generating PR previews from analysis results."""

import logging
import re
from typing import List
from uuid import UUID

from app.schemas.analysis import AnalysisResults, RiskLevel
from app.schemas.shadow_pr import ShadowPRFile, ShadowPRPreview
from app.services.analysis_service import analysis_service

logger = logging.getLogger(__name__)


class ShadowPRService:
    """Service for generating Shadow PR previews."""
    
    def _slugify(self, text: str) -> str:
        """Convert text to URL-friendly slug.
        
        Args:
            text: Text to slugify
            
        Returns:
            Slugified text
        """
        # Convert to lowercase
        text = text.lower()
        # Replace spaces and special chars with hyphens
        text = re.sub(r'[^\w\s-]', '', text)
        text = re.sub(r'[-\s]+', '-', text)
        # Remove leading/trailing hyphens
        text = text.strip('-')
        # Limit length
        return text[:50]
    
    def _generate_branch_name(self, change_description: str) -> str:
        """Generate branch name for Shadow PR.
        
        Args:
            change_description: Change description from analysis
            
        Returns:
            Branch name in format: repotwin/shadow-pr-<slug>
        """
        slug = self._slugify(change_description)
        return f"repotwin/shadow-pr-{slug}"
    
    def _generate_pr_title(self, change_description: str) -> str:
        """Generate PR title.
        
        Args:
            change_description: Change description from analysis
            
        Returns:
            PR title with RepoTwin prefix
        """
        # Capitalize first letter
        title = change_description[0].upper() + change_description[1:] if change_description else ""
        return f"[RepoTwin Shadow PR] {title}"
    
    def _generate_pr_body(
        self,
        change_description: str,
        results: AnalysisResults,
    ) -> str:
        """Generate PR body in markdown format.
        
        Args:
            change_description: Change description
            results: Analysis results
            
        Returns:
            PR body markdown
        """
        risk_emoji = {
            RiskLevel.LOW: "🟢",
            RiskLevel.MEDIUM: "🟡",
            RiskLevel.HIGH: "🟠",
            RiskLevel.CRITICAL: "🔴",
        }
        
        risk_icon = risk_emoji.get(results.risk_assessment.overall_level, "⚪")
        
        body = f"""# Shadow PR Analysis

> **⚠️ This is a Shadow PR generated by RepoTwin**  
> This PR simulates the impact of the proposed change without modifying any code.

## Change Description

{change_description}

## Analysis Summary

{results.summary.overview}

### Key Points

"""
        
        for point in results.summary.key_points:
            body += f"- {point}\n"
        
        body += f"""

## Risk Assessment

**Overall Risk Level:** {risk_icon} **{results.risk_assessment.overall_level.upper()}** (Score: {results.risk_assessment.score}/100)

"""
        
        if results.risk_assessment.factors:
            body += "### Risk Factors\n\n"
            for factor in results.risk_assessment.factors[:5]:  # Top 5 risks
                factor_emoji = risk_emoji.get(factor.level, "⚪")
                body += f"- {factor_emoji} **{factor.name}** ({factor.level})\n"
                body += f"  - {factor.description}\n"
                body += f"  - **Mitigation:** {factor.mitigation}\n\n"
        
        body += f"""

## Impact Radius

- **Files Affected:** {results.impact_radius.metrics.files_affected}
- **Direct Impact:** {results.impact_radius.metrics.files_direct} files
- **Indirect Impact:** {results.impact_radius.metrics.files_indirect} files
- **Functions Affected:** {results.impact_radius.metrics.functions_affected}
- **Classes Affected:** {results.impact_radius.metrics.classes_affected}
- **Codebase Coverage:** {results.impact_radius.metrics.percentage_of_codebase:.1f}%

## Affected Files

"""
        
        for af in results.affected_files[:10]:  # Top 10 files
            impact_emoji = {"direct": "🎯", "indirect": "🔗", "potential": "💡"}
            emoji = impact_emoji.get(af.impact_level.value, "📄")
            body += f"- {emoji} `{af.path}` ({af.impact_level.value})\n"
            body += f"  - {af.reasoning}\n"
        
        if len(results.affected_files) > 10:
            body += f"\n*...and {len(results.affected_files) - 10} more files*\n"
        
        body += """

## Implementation Plan

"""
        
        for phase in results.implementation_plan.phases:
            body += f"### Phase {phase.phase}: {phase.name}\n\n"
            body += f"{phase.description}\n\n"
            body += f"**Estimated Effort:** {phase.estimated_effort}\n\n"
            body += "**Files:**\n"
            for file in phase.files[:5]:
                body += f"- `{file}`\n"
            if len(phase.files) > 5:
                body += f"- *...and {len(phase.files) - 5} more*\n"
            body += "\n"
        
        body += f"""

**Total Estimated Effort:** {results.implementation_plan.total_estimated_effort}

## Test Recommendations

"""
        
        if results.test_recommendations.new_tests_needed:
            body += "### New Tests Needed\n\n"
            for test in results.test_recommendations.new_tests_needed[:5]:
                body += f"- **{test.type}** ({test.priority} priority)\n"
                body += f"  - {test.description}\n"
        
        if results.test_recommendations.existing_tests_to_update:
            body += "\n### Existing Tests to Update\n\n"
            for test in results.test_recommendations.existing_tests_to_update[:5]:
                body += f"- `{test.path}` ({test.priority} priority)\n"
                body += f"  - {test.changes}\n"
        
        body += f"""

## Analysis Metadata

- **Provider:** {results.provider}
- **Enhanced by LLM:** {"✅ Yes" if results.enhanced_by_llm else "❌ No"}

---

**📋 Documentation:** See attached files for detailed analysis
- `REPOTWIN_SHADOW_PR.md` - Main analysis document
- `docs/repotwin/implementation-plan.md` - Detailed implementation guide
- `docs/repotwin/regression-pack.md` - Regression testing strategy
- `docs/repotwin/affected-files.md` - Complete affected files list

**🤖 Generated by RepoTwin** - Powered by IBM Bob
"""
        
        return body
    
    def _generate_main_document(
        self,
        change_description: str,
        results: AnalysisResults,
    ) -> str:
        """Generate main REPOTWIN_SHADOW_PR.md document.
        
        Args:
            change_description: Change description
            results: Analysis results
            
        Returns:
            Document content
        """
        content = f"""# RepoTwin Shadow PR Analysis

## Overview

This document contains the complete Shadow PR analysis for the proposed change.

**Change Request:** {change_description}

## Executive Summary

{results.summary.overview}

### Key Findings

"""
        
        for i, point in enumerate(results.summary.key_points, 1):
            content += f"{i}. {point}\n"
        
        content += f"""

## Risk Assessment

**Overall Risk:** {results.risk_assessment.overall_level.upper()} ({results.risk_assessment.score}/100)

### Identified Risk Factors

"""
        
        for factor in results.risk_assessment.factors:
            content += f"""
#### {factor.name} ({factor.level})

- **Likelihood:** {factor.likelihood}
- **Impact:** {factor.impact}
- **Description:** {factor.description}
- **Mitigation:** {factor.mitigation}
"""
        
        content += """

## Blast Radius Analysis

"""
        
        content += f"""
### Impact Metrics

- Total Files Affected: {results.impact_radius.metrics.files_affected}
- Direct Impact: {results.impact_radius.metrics.files_direct} files
- Indirect Impact: {results.impact_radius.metrics.files_indirect} files
- Functions Affected: {results.impact_radius.metrics.functions_affected}
- Classes Affected: {results.impact_radius.metrics.classes_affected}
- Tests Affected: {results.impact_radius.metrics.tests_affected}
- Codebase Coverage: {results.impact_radius.metrics.percentage_of_codebase:.2f}%

### Affected Files by Impact Level

"""
        
        for af in results.affected_files:
            content += f"""
#### `{af.path}` ({af.impact_level.value})

- **Change Type:** {af.change_type}
- **Reasoning:** {af.reasoning}
- **Complexity Change:** {af.complexity_change}
- **Lines Added:** {af.lines_added}
- **Lines Removed:** {af.lines_removed}
"""
            if af.risk_factors:
                content += "- **Risk Factors:**\n"
                for risk in af.risk_factors:
                    content += f"  - {risk}\n"
        
        content += """

## Regression Analysis

"""
        
        if results.regression_analysis.breaking_changes:
            content += "### Breaking Changes\n\n"
            for bc in results.regression_analysis.breaking_changes:
                content += f"""
#### {bc.type} in `{bc.file}`

- **Severity:** {bc.severity}
- **Description:** {bc.description}
- **Migration Path:** {bc.migration}
"""
        
        if results.regression_analysis.behavior_changes:
            content += "\n### Behavior Changes\n\n"
            for beh in results.regression_analysis.behavior_changes:
                content += f"""
#### {beh.type} in `{beh.file}`

- **Description:** {beh.description}
- **Impact:** {beh.impact}
"""
        
        content += """

---

**Generated by RepoTwin** - Powered by IBM Bob
"""
        
        return content
    
    def _generate_implementation_plan_doc(self, results: AnalysisResults) -> str:
        """Generate implementation plan document.
        
        Args:
            results: Analysis results
            
        Returns:
            Implementation plan document
        """
        content = """# Implementation Plan

## Overview

This document provides a phased approach to implementing the proposed change safely.

"""
        
        content += f"**Total Estimated Effort:** {results.implementation_plan.total_estimated_effort}\n\n"
        
        if results.implementation_plan.prerequisites:
            content += "## Prerequisites\n\n"
            for prereq in results.implementation_plan.prerequisites:
                content += f"- {prereq}\n"
            content += "\n"
        
        content += "## Implementation Phases\n\n"
        
        for phase in results.implementation_plan.phases:
            content += f"""
### Phase {phase.phase}: {phase.name}

**Description:** {phase.description}

**Estimated Effort:** {phase.estimated_effort}

**Files to Modify:**

"""
            for file in phase.files:
                content += f"- `{file}`\n"
            
            content += "\n**Checkpoints:**\n\n"
            for checkpoint in phase.checkpoints:
                content += f"- [ ] {checkpoint}\n"
            content += "\n"
        
        content += f"""

## Rollback Strategy

{results.implementation_plan.rollback_strategy}

---

**Generated by RepoTwin** - Powered by IBM Bob
"""
        
        return content
    
    def _generate_regression_pack_doc(self, results: AnalysisResults) -> str:
        """Generate regression pack document.
        
        Args:
            results: Analysis results
            
        Returns:
            Regression pack document
        """
        content = """# Regression Testing Pack

## Overview

This document outlines the regression testing strategy for the proposed change.

## Test Recommendations

"""
        
        if results.test_recommendations.new_tests_needed:
            content += "### New Tests to Create\n\n"
            for test in results.test_recommendations.new_tests_needed:
                content += f"""
#### {test.type} ({test.priority} priority)

{test.description}

"""
        
        if results.test_recommendations.existing_tests_to_update:
            content += "### Existing Tests to Update\n\n"
            for test in results.test_recommendations.existing_tests_to_update:
                content += f"""
#### `{test.path}` ({test.priority} priority)

**Changes Required:**

{test.changes}

"""
        
        if results.test_recommendations.coverage_gaps:
            content += "### Coverage Gaps\n\n"
            for gap in results.test_recommendations.coverage_gaps:
                content += f"""
#### {gap.area}

- Current Coverage: {gap.current_coverage}%
- Target Coverage: {gap.target_coverage}%
- Gap: {gap.target_coverage - gap.current_coverage}%

"""
        
        content += """

## Regression Test Checklist

"""
        
        for af in results.affected_files[:20]:
            content += f"- [ ] Test `{af.path}` ({af.impact_level.value} impact)\n"
        
        content += """

---

**Generated by RepoTwin** - Powered by IBM Bob
"""
        
        return content
    
    def _generate_affected_files_doc(self, results: AnalysisResults) -> str:
        """Generate affected files document.
        
        Args:
            results: Analysis results
            
        Returns:
            Affected files document
        """
        content = f"""# Affected Files Analysis

## Summary

Total files affected: {len(results.affected_files)}

- Direct impact: {results.impact_radius.metrics.files_direct}
- Indirect impact: {results.impact_radius.metrics.files_indirect}

## Complete File List

"""
        
        for af in results.affected_files:
            content += f"""
### `{af.path}`

- **Impact Level:** {af.impact_level.value}
- **Change Type:** {af.change_type}
- **Complexity Change:** {af.complexity_change}
- **Estimated Changes:** +{af.lines_added}/-{af.lines_removed} lines
- **Reasoning:** {af.reasoning}
"""
            if af.risk_factors:
                content += "- **Risk Factors:**\n"
                for risk in af.risk_factors:
                    content += f"  - {risk}\n"
            content += "\n"
        
        content += """

---

**Generated by RepoTwin** - Powered by IBM Bob
"""
        
        return content
    
    async def generate_shadow_pr_preview(
        self,
        analysis_id: UUID,
    ) -> ShadowPRPreview:
        """Generate Shadow PR preview from analysis results.
        
        Args:
            analysis_id: Analysis UUID
            
        Returns:
            Shadow PR preview
            
        Raises:
            ValueError: If analysis not found or not completed
        """
        logger.info(f"Generating Shadow PR preview for analysis {analysis_id}")
        
        # Get analysis
        analysis = await analysis_service.get_analysis(analysis_id)
        if not analysis:
            raise ValueError(f"Analysis {analysis_id} not found")
        
        if analysis.status.value != "completed":
            raise ValueError(f"Analysis {analysis_id} is not completed (status: {analysis.status})")
        
        # Get analysis results
        results = await analysis_service.get_analysis_results(analysis_id)
        if not results:
            raise ValueError(f"Results for analysis {analysis_id} not found")
        
        # Generate Shadow PR components
        branch_name = self._generate_branch_name(analysis.change_description)
        pr_title = self._generate_pr_title(analysis.change_description)
        pr_body = self._generate_pr_body(analysis.change_description, results)
        
        # Generate files to create
        files_to_create: List[ShadowPRFile] = [
            ShadowPRFile(
                path="REPOTWIN_SHADOW_PR.md",
                content=self._generate_main_document(analysis.change_description, results),
                description="Main Shadow PR analysis document with complete findings"
            ),
            ShadowPRFile(
                path="docs/repotwin/implementation-plan.md",
                content=self._generate_implementation_plan_doc(results),
                description="Detailed phased implementation plan with checkpoints"
            ),
            ShadowPRFile(
                path="docs/repotwin/regression-pack.md",
                content=self._generate_regression_pack_doc(results),
                description="Comprehensive regression testing strategy and checklist"
            ),
            ShadowPRFile(
                path="docs/repotwin/affected-files.md",
                content=self._generate_affected_files_doc(results),
                description="Complete list of affected files with impact analysis"
            ),
        ]
        
        # Generate summary
        summary = f"This Shadow PR simulates {analysis.change_description}. "
        summary += f"It affects {len(results.affected_files)} files with a "
        summary += f"{results.risk_assessment.overall_level.value} risk level. "
        summary += f"Review the attached documentation for detailed analysis."
        
        preview = ShadowPRPreview(
            analysis_id=analysis_id,
            branch_name=branch_name,
            pr_title=pr_title,
            pr_body=pr_body,
            files_to_create=files_to_create,
            summary=summary,
        )
        
        logger.info(f"Shadow PR preview generated for analysis {analysis_id}")
        return preview


# Singleton instance
shadow_pr_service = ShadowPRService()

# Made with Bob
