"""Shadow PR Pydantic schemas."""

from typing import List
from uuid import UUID

from pydantic import BaseModel, Field


class ShadowPRFile(BaseModel):
    """Shadow PR file to be created."""
    path: str = Field(..., description="File path relative to repository root")
    content: str = Field(..., description="File content")
    description: str = Field(..., description="Description of what this file contains")


class ShadowPRPreview(BaseModel):
    """Shadow PR preview response."""
    analysis_id: UUID
    branch_name: str = Field(..., description="Suggested branch name for Shadow PR")
    pr_title: str = Field(..., description="Suggested PR title")
    pr_body: str = Field(..., description="Suggested PR body in markdown format")
    files_to_create: List[ShadowPRFile] = Field(
        default_factory=list,
        description="List of files to create in the Shadow PR"
    )
    summary: str = Field(..., description="Brief summary of the Shadow PR")
    
    class Config:
        json_schema_extra = {
            "example": {
                "analysis_id": "550e8400-e29b-41d4-a716-446655440000",
                "branch_name": "repotwin/shadow-pr-add-reservation-flow",
                "pr_title": "[RepoTwin Shadow PR] Add reservation flow before purchase",
                "pr_body": "## Shadow PR Analysis\n\nThis Shadow PR was generated by RepoTwin...",
                "files_to_create": [
                    {
                        "path": "REPOTWIN_SHADOW_PR.md",
                        "content": "# RepoTwin Shadow PR Analysis...",
                        "description": "Main Shadow PR analysis document"
                    }
                ],
                "summary": "This Shadow PR simulates adding a reservation flow..."
            }
        }

# Made with Bob
